language: java
dist: trusty
os: linux

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn --settings .travis/settings.xml install sonar:sonar -B -V -Pcoverage,sonar

before_install:
    - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXEC --import; fi
    - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXEC --import-ownertrust; fi

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      branch: master

addons:
  sonarcloud:
    organization: sparkmuse-github
    token:
      secure: "qbeuZ9Mw+YDuOcCVIKaQjbEJAoBz/ff8swdov9yXMsrvU9Aq1dr2nCV3POwo9Uam+XEoGruGcdw35ffLiSrgrhBaC6eqyEA7GS9jHVpTNz+8glu8nTbY90m7Uj0L/VwkZuQlQ0BBm0eevLop+OMTOaQOohu+K1IB4Ff9l4n6ki4WVIYgURQgn/qT9bZXMpFoF/CfQd5stdBYHKOQhCYOv3FEJZSNfEY76fMshIkaAEVYqSJ38GwgAflOdhCDy48rILXqMDuG78ek2UBbiM31AacEohTCyTvhNIeE5/mYgUWEOm3le4sB2a2IMlc8oiXSgwlE2VdzjU6GXJGGgzbo5pvf6mcciJ2shZ4gJEobSqGxUHhhPjnVjv4xdGLe9aJh25SMeaq3ZtGUFok/tdalPEIbZVXG+VbXGFdI+2p7sg6YNW5IbsQ8WDd6FDE7VGr69vEKuD+Ejb/grShb7LCP5cRM4fInHi1GPevT4ZF+wfUiGZscCh20x5xGjgZScsEvslmaqjrLnbRQhGkJCo6EDDwY/zikQ/2iIIApK60uuLLjR6F2YaBk9ncNMo73oDn0gW7NHPgI3RMESMY4FspVgsEPgDuxQwPp1Ez+0sN0FGtisqqwAMMlMST1oSsRNWNtAoR3e9WWBD11JpVBO3ZDqS418q/mlHol+NZseeZtkcI="

env:
    global:
     # GPG_EXEC
    - secure: "GO8yBXGiD0/XAfQRtnR9kIb5Kckyn8jcHsgsgNqSPqx9hU/vtzhd2W3nKDtxOuyxOclpSfrNuNVoUtEZ6sfgwvp6+O28Z4wa4Rl6BQGlKT52tYpRoCbU5QwzALujr+mJccCYI7s50ZaJlArUyGL5DoBEVZFXty9y4thPDGTvQxlckKq7lLAy5hcHwpegPN9UEykDzjvkPJ+RZ+6AcUYU8H4E+JRPFC4GNJ1dHblXSCa+pg2Bhzqt9BPno58ohRjl1GjGJLkndzNjrWfPTc/22Nziko0AJqIbhsMwpr2Yqm+MeNIlVgZ8vIZrYPFbu5cbAaTGEKZwVV3NXdERrfkvyTU+jN+7K3xmH+psOarIj984/xYSWQFT62jTE+XsLGWKgGeCgP8llXZzInxJ8gIf68i8XO52hKmv0orDKunjXdX4ph7ygJVj1JCS+uOqT/BQhJmwBKh3/y7faxpcO2B5ZCPt1RtFBjoPDOWrz6K+kLbeHRpd5+nNsu0lvlMKVTwO2KGa6X5bdHaF4BNAnGsI8ahf0a0ZdUE+HbtuAI1Oi3ex6NjbwBJCyH2YrLo/fHwriUHPGfXXx+PgfcVn4Hepz/VRXrdIlzlhmwlGmRIKrWA4uecfTb5WhTzNsgz0V15u1Sz9oFNTcR+2QozdnaH01cWOf6bP/T+FEO5y3WDUQ90="
     # GPG_OWNERTRUST
    - secure: "iPl593yQUsFffjkCaifFC5W2CZWcbjr4GFwA1ZGG6btVudvvJuQXb/eSoaF6bz5VuG4XrYJxacm/4XJ1wGP4Bq0/NO1YOaEw/mMnr/JpBtfsE8iIyHgd66RLyGWk3cwxKJEGsQVkXDgtGGnkmXF7rFHw0gzqFVUspKCoTgYqMnjA60U6O2obKaxwQY3y+U7VOZ7Tft+qfYlb0wvgypPbJQXivLX543bZokbHFlNphsc9xJo3bZlckgY1RbulN3Pqi1wrrdJZpnf7f1s/m0fD+PHKC7E3EHhW+bGa4yLgGV0tyJInnVwdAFN/5+1rXcjBeyXu5d+NumUclR36FzaFJUFwCBTQnr8VpNZvwk9+Y8vMYeYmdht1cZfFfBOqSYJW0gquflNzKEKA9IHJrYSAApbHkHQlI7vxw2hMjksWJdmLYsUVZbBUX1GII4dRf+SzXmgYXCiOHxo3JhQrw32bTV03+lhexRIj85v6yYS68CKev+oWaVZTFrjvpEHwOBG3G5FGtrUzgnHS4WcmmcW559PcwQlEiO8TFgBaq0+AkFaqCVVvtRc0S8OSH8Z/4EOiTYXkpsiDuFG7zu+W+8EB8XamQWy2/N/QmFAFDgi/zdePedZl/0dZw7vPFS3OLqoCDEDVA2/QEq4y1JJCcxYY4NIM7oQ+q+KZXEdH9YzLrYo="
     # GPG_PASSPHRASE
    - secure: "uNKAcJGkj0JWk9fzu3rL8tpLGxu+AXK4KIeZmKxUl5P18Nt1ZDfL7amtl/uRImeh4W4dz4h3j6IIx+sxEoG34UKrx5rfEKgnCWivH7I7AN5PAkWlnDH6kwjcfXqKh1aFncq6yW27/wo3639o6QM7Ua71CSgEUzpSQDye5MavfWY5ynKa6w06UFIH6COj5c0kACNtVgFHziWMPd0JMNpJ0vNyIYGMCkPVnZrD940nTYLEiwn/L6Y/F/nlNHoNO6j0f5UwGOKLwP+DfRvY3bc1euZnzg2uhE1GriacEkNW9AKoLJCGFI/eSbml5WW5+vUEDTOt457CFhh23iWcAXobLkPfIb+Uarh7C8MtCYiMATduA5Ubh5KZQ08ttM0JsvedRVrZz1FiszNDvbNAfgW43O+wkxlCgVn9vx1XVlBB4h6UgzdghZEPwVDFH7wyYC5jJ1L6ue78b/8P9q/kMFNW0IkHE/CXSV8+z2kvV8zhgYMmtRKthiA6BxFDZXNV8P+k7G3fuFYwhHr4mEePMQwPZ4o6Erq3hfOrohzDUNezoA9/mr7idnaLqNDBb1grEt3nLgpZT/X8sM4dbDKmBmx4JCX/N1Zg4KJrdv6zYBAH2eOcdTmwNNiA7DKWtOdajwtVTpzuVtrqitpjWe+XkZMkPDXpXBKXOD6aH8v00DlN8ew="
     # GPG_SECRET_KEYS (set online value too large)
     # NEXUS_PASSWORD
    - secure: "BKjvHZtaUqFG1ob2bi6l6z4WEJ1oBPffFr2ewxGDvRYwwaOB/AROKAq5zJQGl6y8Em18mc5xMQtTQMfeCzWAJOfi+cdVcPdfhp8oC8Dm8iYU2a5Y2RSBdt5R4IHZXqQ5wve+wRTmpy/nB7bLfWmgqNZ2D6B68tKZfspT46ZQm2AIitwDOVGoPNtqJLD1aXqfGmhsbMQY6eCQAdijgkvK9baedStDVWVYtMOn7k4w7o8AThOAALL4OWzJZdhFH9oPPGo43m9B/o3RtYRh+QeSIyeAqYeLOmP0mgTPwSpOwNWNrWNS1fQPd3WiKxlok75mRoTZ9utLzRnlycCEul7YcjWMBxesxfn6UOn66b90mJIJKApOXiRdCW9hcix2Esp49ZOq6NBz8qPNmuAWyJaieqOox3+m4W4OoVbmVl3xW06si+c3oj/2jSTvzvZ6I3beqWTijUvByDZ/wObY3RPMC4fidUAGLdvGtpNCwsHMSUbHJa7amtq2QKvXByWuHYAupCWn/n6yGlLTqJOJkq3sO5CCPpPna+7+gjIVrml8mbyvIwA10D0Nw/GCSjbraPwU6NP0Ql4R31sBXOc6YP4dQB+S7rek4y8yTxL7NH6NO0sflvSbjVcS0Kq8bZzCI8A/uYogN3e/268PXvSfR1lkQEZ+XkGlN1uqLu6hREiXxCk="
     # NEXUS_USERNAME
    - secure: "PqpC3AGtPeGK33XUqYwLRHVSTXcTEsMdErchcLyNHegUp6lIwCc0cNha7Ryd64DjfJdFw6sFInzT6deDzAyEXUQ8vyEJMUmYMVoSE+lFkR1tr+bfje1l/y4ZJrUZlWPTwfwB/Fg/Ve2BYy2+PFmnripOhhMcvQGmXh31uxVO3ytRlzqCo2ESbF+ZJ8ALVqRZeF2Goge0OugXZJxkbgTiz9V2/rVvAilYGLEs9lbuACekLWhB5O+Vs3o6HiAvFSqlLRLfpfaKiUAq+LO5A1OuoiRkvEdho3/vmEBTgWfvYNgyD7nLaHjMetOA7yPSgndzbkcx34wEHDNHBBJ5kQbk/fpWxuljQwZZMHNDwI4ZT4Hl/SealXZfMSPYoVVnVaxUFHMKr7tb0TvvxnLWvEFaQ40Ua0UkM/fvIXpA7lWjwW98osGAhvPyUAts5y2edDIh2RVwlgNWiuSIACSLDipMjOXyLe9dcQjN32YvSzXOKz+QI6pqe93NhEsjViCZ6XYwzN+eZaI9bfkr234ipEkDweyM4x1XU7hlqkz+MVXRao03+DfAqadVZkauUnZ3xjCGEedxIMqqBeAopAjdum+Km342tiF4cnU1tZJVZDaGEmBIhhupjDcgsJ8YJ0WrTfDCpaPQryTs7x7M+YeTTUGNnb0pKuMKWL93j3UHD9wPTPQ="
